version: '2'

services:
  app:
    image: &app async-tcp-chat-client
    mem_limit: 500M
    build:
      context: ./
      dockerfile: Dockerfile
    command: python reader.py
    volumes:
      - ./:/app
    restart: always

  gui:
    image: *app
    build:
      context: ./
      dockerfile: Dockerfile
    command: python app.py
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ./:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
